version: '3'
services:
  lipid_gem:
    image: kapamais/lipid_gema:lipid_gema_db
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /Lipid_GEM:/data
    networks:
      - app

  code_container:
    image: kapamais/lipid_gema:lipid_gema_anotator
    volumes:
      - ../Annotation/models/models_annotated:/Annotation/models/models_annotated
      - ../Annotation/models/models_case_study:/Annotation/models/models_case_study
      - ../Annotation/models/results:/Annotation/models/results
    depends_on:
      - lipid_gem
    networks:
      - app

networks:
  app:
    driver: bridge